codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default: false
      linux:
        threshold: 1%
        flags:
          - linux
      windows:
        threshold: 1%
        flags:
          - windows
      linux-strategies:
        threshold: 1%
        flags:
          - linux-strategies
      windows-strategies:
        threshold: 1%
        flags:
          - windows-strategies
    patch:
      default:
        threshold: 5%
    changes: false
