image: docker:20.10.8

stages:
  - build

services:
    - docker:20.10.8-dind

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

docker-build:
  stage: build
  tags:
    - docker

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build
      --label "git-commit-sha=$CI_COMMIT_SHA"
      --label "git-commit-branch=$CI_COMMIT_BRANCH"
      --label "git-commit-timestamp=$CI_COMMIT_TIMESTAMP"
      --label "git-commit-title=$CI_COMMIT_TITLE"
      -t $IMAGE:$CI_COMMIT_SHORT_SHA
      -t $IMAGE:latest .

  after_script:
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE:latest

  only:
    - master
    - merge_request
