# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  # Set very long to support 1-sentence-per-line style.
  line_length: 999
  # Number of characters for headings (match that of black's default)
  heading_line_length: 88
  # Number of characters for code blocks (match that of black's default)
  code_block_line_length: 88
