version: "3.6"

services:
  ontoapi:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env

  redis:
    image: redis

  sftp:
    image: "emberstack/sftp"    
    volumes:
      - ./.sftp_conf.json:/app/config/sftp.json:ro
      - sftp-data:/home/${SFTP_USER}

volumes:
  sftp-data: