version: "3"
services:
  oteapi:
    image: ontotrans/oteapi-development:latest
    ports:
      - 8080:8080
    volumes:
      - <path-to-oteapi>:/app
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis-persist:/data
  sftp:
    image: atmoz/sftp
    volumes:
      - sftp-storage:/home/foo/upload
    expose:
      - "22"
    command: foo:pass:1001
volumes:
  redis-persist:
  sftp-storage:

