version: "3.6"

services:
  ontoapi:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
      - datadirectory:/app/data
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env

  sftp:
    image: "emberstack/sftp"
    volumes:
      - ./.sftp_conf.json:/app/config/sftp.json:ro
      - datadirectory:/app/data

  broker:
    image: rabbitmq:3.8.12-alpine

  tasks:
    build:
      context: .
      target: development
      dockerfile: Dockerfile_tasks
    volumes:
      - ".:/app"
    env_file:
      - .env

  redis:
    image: redis

volumes:
  datadirectory:
