version: "3.6"

services:
  ontoapi:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: redis
    ports:
      - "6379:6379"

  sftp:
    image: "emberstack/sftp"
    ports:
      - "${SFTP_PORT}:22"
    volumes:
      - ./.sftp_conf.json:/app/config/sftp.json:ro
      - sftp-data:/home/${SFTP_USER}

volumes:
  sftp-data:

networks:
  default:
    external:
      name: scinet
