default:
  image: docker

stages:
  - test
  - build

variables:
  IMAGE: $CI_REGISTRY_IMAGE/fastapidemo
    

docker-build:
  stage: build
  tags:
    - docker

  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    
  script:
    - docker pull $IMAGE:latest
    - docker build --target production --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest

  only:
    - master

unittest:
  image: python:3.8.3-slim-buster
  stage: test
  tags:
    - OntoTrans

  script:
    - pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pip
    - pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt
    - pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pytest
    - pytest -v --junitxml="test-results/test-fastapi.xml"
  artifacts:
    when: always
    
    reports:
      junit:
        - test-results/test-*.xml
