name: CD - Publish

on:
  release:
    types:
    - published

jobs:
  publish:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.4.0
    if: github.repository == 'EMMC-ASBL/oteapi-core' && startsWith(github.ref, 'refs/tags/v')
    with:
      # General
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      release_branch: master

      # Publish to PyPI
      python_package: true
      package_dirs: oteapi
      python_version_build: "3.9"
      install_extras: "[dev]"
      build_cmd: "python -m build"
      publish_on_pypi: true

      # Documentation
      update_docs: true
      python_version_docs: "3.9"
      doc_extras: "[docs]"
    secrets:
      PyPI_token: ${{ secrets.PYPI_TOKEN }}
      PAT: ${{ secrets.RELEASE_PAT }}
