name: CD - Publish

on:
  release:
    types:
    - published

env:
  PUBLISH_UPDATE_BRANCH: master
  GIT_USER_NAME: "TEAM 4.0[bot]"
  GIT_USER_EMAIL: "Team4.0@SINTEF.onmicrosoft.com"

jobs:

  update-repo-and-release:
    name: Update CHANGELOG and documentation
    runs-on: ubuntu-latest
    if: github.repository == 'EMMC-ASBL/oteapi-core' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -U setuptools wheel build
        pip install -U -e .

    - name: Update changelog
      uses: CharMixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release_branch: ${{ env.PUBLISH_UPDATE_BRANCH }}

    - name: Update documentation and version - Commit changes and update tag
      run: .github/utils/update_publish.sh

    - name: Update '${{ env.PUBLISH_UPDATE_BRANCH }}'
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.RELEASE_PAT }}
        branch: ${{ env.PUBLISH_UPDATE_BRANCH }}
        sleep: 15
        force: true
        tags: true
        unprotect_reviews: true

    - name: Get tagged versions
      run: echo "PREVIOUS_VERSION=$(git tag -l --sort -version:refname | sed -n 2p)" >> $GITHUB_ENV

    - name: Create release-specific changelog
      uses: CharMixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release_branch: ${{ env.PUBLISH_UPDATE_BRANCH }}
        since_tag: "${{ env.PREVIOUS_VERSION }}"
        output: "release_changelog.md"

    - name: Append changelog to release body
      run: |
        gh api /repos/${{ github.repository }}/releases/${{ github.event.release.id }} --jq '.body' > release_body.md
        cat release_changelog.md >> release_body.md
        gh api /repos/${{ github.repository }}/releases/${{ github.event.release.id }} -X PATCH -F body='@release_body.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build source distribution
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

  # docs:
  #   name: Deploy release documentation
  #   # needs: publish
  #   needs: update-repo-and-release
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #       ref: ${{ env.PUBLISH_UPDATE_BRANCH }}

  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - name: Install Python dependencies
  #     run: |
  #       python -m pip install -U pip
  #       pip install -U setuptools wheel
  #       pip install -U -e .[docs]

  #   - name: Set git config
  #     run: |
  #       git config --global user.name "${{ env.GIT_USER_NAME }}"
  #       git config --global user.email "${{ env.GIT_USER_EMAIL }}"

  #   - name: Deploy documentation
  #     run: |
  #       mike deploy --push --remote origin --branch gh-pages --update-aliases --config-file mkdocs.yml ${GITHUB_REF#refs/tags/v} stable
  #       mike deploy --push --remote origin --branch gh-pages --update-aliases --config-file mkdocs.yml latest main
