name: CI - Check dependencies

on:
  schedule:
    - cron: "30 5 * * 1"
  workflow_dispatch:

jobs:
  check-dependencies:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_check_pyproject_dependencies.yml@v2.7.2
    if: github.repository_owner == 'EMMC-ASBL'
    with:
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      permanent_dependencies_branch: ci/dependabot-updates
      python_version: "3.9"
      install_extras: "dev"
      pr_labels: "CI/CD"
      ignore: |
        dependency-name=agraph-python...version=>101.0.7
        dependency-name=celery...version==>=6
        dependency-name=diskcache...version==>=6
        dependency-name=numpy...version==>=2
        dependency-name=openpyxl...version==>=4
        dependency-name=Pillow...version==>=11
        dependency-name=pydantic...version==>=2
        dependency-name=requests...version==>=3
        dependency-name=urllib3
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
