name: CI/CD - New updates to 'master'

on:
  push:
    branches: [master]

jobs:
  updates-to-master:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.5.2
    if: github.repository_owner == 'EMMC-ASBL'
    with:
      # General
      git_username: "TEAM 4.0[bot]"
      git_email: "Team4.0@SINTEF.no"
      default_repo_branch: master

      # Update permanent dependencies branch
      permanent_dependencies_branch: ci/dependabot-updates

      # Documentation
      update_docs: true
      update_python_api_ref: true
      package_dirs: oteapi
      update_docs_landing_page: true
      python_version: "3.9"
      doc_extras: "[docs]"
      full_docs_dirs: |
        models
        strategies/download
        strategies/filter
        strategies/mapping
        strategies/parse
        strategies/resource
        strategies/transformation
      landing_page_replacements: |
        (LICENSE),(LICENSE.md)
        scheme\`](oteapi/models/resourceconfig.py),scheme\`][oteapi.models.resourceconfig.ResourceConfig.downloadUrl]
        mediaType\`](oteapi/models/resourceconfig.py),mediaType\`][oteapi.models.resourceconfig.ResourceConfig.mediaType]
        accessService\`](oteapi/models/resourceconfig.py),accessService\`][oteapi.models.resourceconfig.ResourceConfig.accessService]
        (oteapi/models/filterconfig.py),[oteapi.models.filterconfig.FilterConfig.filterType]
        (oteapi/models/functionconfig.py),[oteapi.models.functionconfig.FunctionConfig.functionType]
        (oteapi/models/mappingconfig.py),[oteapi.models.mappingconfig.MappingConfig.mappingType]
        (oteapi/models/transformationconfig.py),[oteapi.models.transformationconfig.TransformationConfig.transformationType]
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
